modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="stoneholm"
version="${version}"
displayName="Stoneholm"
authors="TheGrimsey"
description="Underground villages."
logoFile="assets/stoneholm/icon.png"

[[dependencies.stoneholm]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stoneholm]]
    modId="minecraft"
    type="required"
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stoneholm]]
    modId="cloth_config"
    type="required"
    versionRange="[${cloth_config_major},)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="stoneholm.mixins.json"
