    modLoader="javafml" #mandatory
    loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
    license="MIT"

    [[mods]]
      modId="stoneholm"
      version="1.3"
      displayName="Stoneholm"
      authors="TheGrimsey"
      description='''
        Do you love villages? Ever wonder why no villagers have decided to settle underground in some sort of inhabited Stronghold? Well, you can stop wondering because now they do.
        '''

      [[dependencies.stoneholm]]
        modId="forge"
        mandatory=true
        versionRange="[39,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.stoneholm]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.18,1.19)"
        ordering="NONE"
        side="BOTH"
        
      [[dependencies.stoneholm]]
        modId="cloth_config"
        mandatory=true
        versionRange="[6.0,)"
        ordering="NONE"
        side="BOTH"